### ISSUE TITLE
тесты падают

### ISSUE THREAD

**Issue by rptl8sr** [larkovsasha/sprint1#1]
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/efdfd5be-40f0-4a85-80f6-d93f63923bf5" />

хотя в целом всё норм по сервису

**Comment by larkovsasha** [comment]
Исправил, в задании просто одна ошибка неверного выражения, а я их разбил на несколько, а в тестах забыл поправить. Проверь пожалйста еще раз.

**Comment by rptl8sr** [comment]
Да, ок всё, не падают :)
